auto discover version
jlund/ansible-go pull request #34
Opened 2018-02-26 00:47 UTC by yogo1212

cont https://github.com/jlund/ansible-go/pull/28

2018-02-26 09:19 UTC, yogo1212 commented
there's more

2018-02-26 18:19 UTC, yogo1212 commented
something about those comments in the defaults yml just makes adding hunks impossible..

2018-02-26 20:53 UTC, yogo1212 commented
k - i'm done :-p

you might want to ask about splitting this PR ;-)

2018-03-17 19:17 UTC, yogo1212 commented
is it that bad? :confused:

2018-05-02 20:12 UTC, yogo1212 commented
@jlund are you still active in this repo?

2018-06-14 13:13 UTC, evrardjp commented
good question @yogo1212 but I haven't seen an answer to my first PR asking for the same thing. What have you done since then?

2018-06-14 13:15 UTC, evrardjp commented
This series of patch can probably be reduced to 2 or 3 commits, but I generally like them. 👍 .

2018-06-18 08:51 UTC, yogo1212 commented
@evrardjp i've implemented the signature check, "streamlined" vars and defaults, and slightly refactored some of the code.

2018-08-01 12:56 UTC, evrardjp requested changes
Can you squash all those commits into one?

2018-08-01 12:56 UTC, evrardjp commented on tasks/main.yml
> +    shell:
probably need a > there?

2018-08-01 12:56 UTC, evrardjp commented on tasks/install_go.yml
> +  file: state=directory path="{{ go_download_dir }}" mode=0755
it would be clearer to use the yaml format here too.

2018-08-01 15:32 UTC, yogo1212 commented on tasks/main.yml
> +    shell:
maybe.. where exactly? :-p

2018-08-01 15:33 UTC, yogo1212 commented on tasks/install_go.yml
> +  file: state=directory path="{{ go_download_dir }}" mode=0755
done that (5c02ea3)

2018-08-01 15:36 UTC, yogo1212 commented
i can squash but i'd rather wait until right before the merge.
it was surprising to see any activity at all from this repo ;-)

2018-08-09 16:22 UTC, evrardjp commented
@yogo1212 same. But I think it's better if we are working together than having a bazillion roles doing the same thing. :)

2018-08-09 16:24 UTC, evrardjp commented on tasks/main.yml
> +    shell:
the shell command is on a new line, so it makes sense to me to have >- or | at line 4. But I might be wrong and ansible might be smart there. Just an habit I'd say :)

2018-10-06 08:33 UTC, evrardjp commented
thanks for the change :)

2018-12-27 12:52 UTC, yogo1212 commented
https://github.com/jlund/ansible-go/issues/37

2019-04-12 12:06 UTC, closed without merging